name: CI
on:
  push:
    paths-ignore:
      - "doc/**"
      - "README.md"
      - "**.md"
      - "LICENSE**"
  pull_request:
    paths-ignore:
      - "doc/**"
      - "README.md"
      - "**.md"
      - "LICENSE**"
jobs:
  x86_64-linux:
    runs-on: ubuntu-latest
    # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push
    # to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    env:
      DISPLAY: ':99.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 2024.5.0-mach
          mirror: 'https://pkg.machengine.org/zig'
      # - name: x86_64-linux -> x86_64-linux-musl
      #   run: zig build -Dtarget=x86_64-linux-musl
      - name: x86_64-linux -> x86_64-macos
        run: zig build -Dtarget=x86_64-macos
      - name: x86_64-linux -> aarch64-macos
        run: zig build -Dtarget=aarch64-macos
      - name: x86_64-linux -> x86_64-windows
        run: zig build -Dtarget=x86_64-windows-gnu
      - name: launch xvfb
        run: Xvfb :99 -screen 0 1680x720x24 > /dev/null 2>&1 &
      # TODO: do we actually need this?
      - name: install Linux dependencies
        run: |
          sudo add-apt-repository -y ppa:kisak/kisak-mesa
          sudo apt-get update
          sudo apt-get install mesa-utils mesa-utils-extra mesa-va-drivers mesa-vdpau-drivers mesa-vulkan-drivers xvfb pulseaudio jackd
      - name: test
        run: zig build test
      - name: test (with core deps only)
        run: zig build -Dcore test
      - name: test (with sysaudio deps only)
        run: zig build -Dsysaudio test
      - name: test (with sysgpu deps only)
        run: zig build -Dsysgpu test
      - name: test (specific deps only)
        run: zig build -Dcore -Dsysaudio -Dsysgpu test
      - name: 'sysgpu: validate spirv code generation'
        run: |
          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list http://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
          sudo apt update
          sudo apt install vulkan-sdk spirv-tools
      - name: 'sysgpu: validate spirv output'
        run: bash ./src/sysgpu/tools/validate_spirv.sh
  x86_64-windows:
    runs-on: windows-latest
    # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push
    # to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 2024.5.0-mach
          mirror: 'https://pkg.machengine.org/zig'
      - name: test
        run: zig build test
  x86_64-macos:
    runs-on: macos-12
    # We want to run on external PRs, but not on our own internal PRs as they'll be run by the push
    # to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 2024.5.0-mach
          mirror: 'https://pkg.machengine.org/zig'
      - name: Workaround Zig Bug
        run: brew uninstall --ignore-dependencies libx11 # https://github.com/ziglang/zig/issues/11066
      - name: test
        run: zig build test
